language: clojure

env:
  global:
    - BOOT=$HOME/.boot/cache/boot

install: |
  if ! [[ -x $BOOT ]]; then
    curl -fsSLo $BOOT https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
    chmod 0755 $BOOT
  fi
  $BOOT

script:
  - $BOOT test

cache:
  directories:
  - $HOME/.m2
  - $HOME/.boot/cache
